- name: configure MYSQL
  hosts: mysql
  become: yes
  vars:
    root_password: "ExpenseApp@1"
  tasks:
  - name: Installing MYSQL server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Start and enable MYSQL server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Try to create database as root/nopassword first. If not allowed, pass the credentials
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{ root_password }}"
      login_host: mysql.deaws82s.online
      ignore_errors: true
    register: mysql_info

  - name: print the mysql_info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setting up root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ root_password }}"
